## Harjoitustyö

## Vaihe 1

#### Tehtävä 1. Hae Digitrafficin REST-rajapintapalvelusta (JSON-formaatissa) aktiiviset junat pääteosoitteella `/live-trains` Helsingin asemalta, joiden hakuparametrit ovat seuraavat:
* arrived_trains=10
* departed_trains=10
* include_nonstopping=False

In [1]:
import requests

url = 'https://rata.digitraffic.fi/api/v1/live-trains/station/HKI?arrived_trains=10&departed_trains=10&include_nonstopping=False'
req_juna = requests.get(url=url)
req_juna.url
req_juna.status_code
juna_data = req_juna.json()
#juna_data

#### Tehtävä 2. Tämän jälkeen lue kyseinen data Pandasin dataframeen ilman muokkaamista, jolloin sarakkeiden otsikot ovat seuraavanlaiset:

 `cancelled`,
 `commuterLineID`,
 `departureDate`,
 `operatorShortCode`,
 `operatorUICCode`,
 `runningCurrently`,
 `timeTableRows`,
 `timetableAcceptanceDate`,
 `timetableType`,
 `trainCategory`,
 `trainNumber`,
 `trainType`,
 `version`

In [2]:
import pandas as pd

junat_df = pd.DataFrame(juna_data)
junat_df

,trainNumber,departureDate,operatorUICCode,operatorShortCode,trainType,trainCategory,commuterLineID,runningCurrently,cancelled,version,timetableType,timetableAcceptanceDate,timeTableRows
0,7,2025-01-29,10,vr,IC,Long-distance,,True,False,290367456343,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
1,38,2025-01-29,10,vr,IC,Long-distance,,True,False,290367451534,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'OL', 'stationUICCode': ..."
2,47,2025-01-29,10,vr,IC,Long-distance,,True,False,290367442254,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
3,959,2025-01-29,10,vr,IC,Long-distance,,False,False,290367374221,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
4,8126,2025-01-29,10,vr,HL,Commuter,A,False,False,290367394470,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'LPV', 'stationUICCode':..."
5,8128,2025-01-29,10,vr,HL,Commuter,A,True,False,290367449684,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'LPV', 'stationUICCode':..."
6,8133,2025-01-29,10,vr,HL,Commuter,A,True,False,290367452892,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
7,8135,2025-01-29,10,vr,HL,Commuter,A,False,False,290367453973,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
8,8356,2025-01-29,10,vr,HL,Commuter,E,True,False,290367454812,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'KLH', 'stationUICCode':..."
9,8359,2025-01-29,10,vr,HL,Commuter,E,True,False,290367455920,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
10,8587,2025-01-29,10,vr,HL,Commuter,Y,True,False,290367459099,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
11,8681,2025-01-29,10,vr,HL,Commuter,P,False,False,290367404269,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
12,8683,2025-01-29,10,vr,HL,Commuter,P,False,False,290367444076,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
13,8689,2025-01-29,10,vr,HL,Commuter,P,True,False,290367452451,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
14,8691,2025-01-29,10,vr,HL,Commuter,P,True,False,290367443380,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
15,8881,2025-01-29,10,vr,HL,Commuter,I,False,False,290367369444,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
16,8883,2025-01-29,10,vr,HL,Commuter,I,False,False,290367424809,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
17,8884,2025-01-29,10,vr,HL,Commuter,I,True,False,290367456343,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
18,8891,2025-01-29,10,vr,HL,Commuter,I,True,False,290367450596,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
19,8892,2025-01-29,10,vr,HL,Commuter,I,False,False,290367453486,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
20,9214,2025-01-29,10,vr,HL,Commuter,K,False,False,290367422006,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'KE', 'stationUICCode': ..."
21,9218,2025-01-29,10,vr,HL,Commuter,K,True,False,290367455920,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'KE', 'stationUICCode': ..."
22,9237,2025-01-29,10,vr,HL,Commuter,K,True,False,290367455920,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
23,9239,2025-01-29,10,vr,HL,Commuter,K,False,False,290367411514,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
24,9676,2025-01-29,10,vr,HL,Commuter,R,False,False,290367366483,REGULAR,2024-08-16T07:34:07.000Z,"[{'stationShortCode': 'RI', 'stationUICCode': ..."
25,9695,2025-01-29,10,vr,HL,Commuter,R,True,False,290367456343,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
26,9840,2025-01-29,10,vr,HL,Commuter,Z,False,False,290367402169,REGULAR,2024-08-16T07:34:07.000Z,"[{'stationShortCode': 'LH', 'stationUICCode': ..."
27,9849,2025-01-29,10,vr,HL,Commuter,Z,False,False,290367441775,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
28,64420,2025-01-29,10,vr,W,Shunting,,False,False,290367364721,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'ILR', 'stationUICCode':..."
29,64422,2025-01-29,10,vr,W,Shunting,,False,False,290367394897,REGULAR,2024-10-31T06:14:29.000Z,"[{'stationShortCode': 'ILR', 'stationUICCode':..."

#### Tehtävä 3. Poista kaikki muut sarakkeet paitsi `timeTableRows` ja `trainNumber`

In [3]:
train_info = junat_df.drop(["cancelled", "commuterLineID", "departureDate", 
                     "operatorShortCode", "operatorUICCode", "runningCurrently", 
                     "timetableAcceptanceDate", "timetableType", "trainCategory", 
                     "trainType", "version"], axis=1)
train_info

    trainNumber                                      timeTableRows
0             7  [{'stationShortCode': 'HKI', 'stationUICCode':...
1            38  [{'stationShortCode': 'OL', 'stationUICCode': ...
2            47  [{'stationShortCode': 'HKI', 'stationUICCode':...
3           959  [{'stationShortCode': 'HKI', 'stationUICCode':...
4          8126  [{'stationShortCode': 'LPV', 'stationUICCode':...
5          8128  [{'stationShortCode': 'LPV', 'stationUICCode':...
6          8133  [{'stationShortCode': 'HKI', 'stationUICCode':...
7          8135  [{'stationShortCode': 'HKI', 'stationUICCode':...
8          8356  [{'stationShortCode': 'KLH', 'stationUICCode':...
9          8359  [{'stationShortCode': 'HKI', 'stationUICCode':...
10         8587  [{'stationShortCode': 'HKI', 'stationUICCode':...
11         8681  [{'stationShortCode': 'HKI', 'stationUICCode':...
12         8683  [{'stationShortCode': 'HKI', 'stationUICCode':...
13         8689  [{'stationShortCode': 'HKI', 'stationUICCode':...
14         8691  [{'stationShortCode': 'HKI', 'stationUICCode':...
15         8881  [{'stationShortCode': 'HKI', 'stationUICCode':...
16         8883  [{'stationShortCode': 'HKI', 'stationUICCode':...
17         8884  [{'stationShortCode': 'HKI', 'stationUICCode':...
18         8891  [{'stationShortCode': 'HKI', 'stationUICCode':...
19         8892  [{'stationShortCode': 'HKI', 'stationUICCode':...
20         9214  [{'stationShortCode': 'KE', 'stationUICCode': ...
21         9218  [{'stationShortCode': 'KE', 'stationUICCode': ...
22         9237  [{'stationShortCode': 'HKI', 'stationUICCode':...
23         9239  [{'stationShortCode': 'HKI', 'stationUICCode':...
24         9676  [{'stationShortCode': 'RI', 'stationUICCode': ...
25         9695  [{'stationShortCode': 'HKI', 'stationUICCode':...
26         9840  [{'stationShortCode': 'LH', 'stationUICCode': ...
27         9849  [{'stationShortCode': 'HKI', 'stationUICCode':...
28        64420  [{'stationShortCode': 'ILR', 'stationUICCode':...
29        64422  [{'stationShortCode': 'ILR', 'stationUICCode':...

#### Tehtävä 4. Tämän jälkeen pura `timeTableRows` sarakkeen arvot jokaisesta junasta erikseen (sarakkeen arvo jokaiselle junalle sisältää useampia JSON-objekteja) ja lisää dataan mukaan junan tiedot yksilöivä `trainNumber`

In [4]:
from pandas import json_normalize

timetable_df = pd.DataFrame()

# Käy läpi alkuperäisen DataFrameen rivit
for index, row in junat_df.iterrows():
    train_number = row['trainNumber']
    time_table_rows = row['timeTableRows']
    
    # Purkaa JSON-tiedot ja lisää ne uuteen DataFrameen
    train_df = json_normalize(time_table_rows)
    train_df['trainNumber'] = train_number
    
    timetable_df = pd.concat([timetable_df, train_df], ignore_index=True)
timetable_df

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialStop,commercialTrack,cancelled,scheduledTime,actualTime,differenceInMinutes,causes,trainReady.source,trainReady.accepted,trainReady.timestamp,liveEstimateTime,estimateSource,trainNumber
0,HKI,1,FI,DEPARTURE,True,True,9,False,2025-01-29T13:19:00.000Z,2025-01-29T13:19:16.000Z,0.0,[],KUPLA,True,2025-01-29T13:04:24.000Z,NaN,NaN,7
1,PSL,10,FI,ARRIVAL,True,True,4,False,2025-01-29T13:24:00.000Z,2025-01-29T13:24:06.000Z,0.0,[],NaN,NaN,NaN,NaN,NaN,7
2,PSL,10,FI,DEPARTURE,True,True,4,False,2025-01-29T13:25:00.000Z,2025-01-29T13:25:48.000Z,1.0,[],NaN,NaN,NaN,NaN,NaN,7
3,KÄP,977,FI,ARRIVAL,False,NaN,,False,2025-01-29T13:27:00.000Z,2025-01-29T13:28:07.000Z,1.0,[],NaN,NaN,NaN,NaN,NaN,7
4,KÄP,977,FI,DEPARTURE,False,NaN,,False,2025-01-29T13:27:00.000Z,2025-01-29T13:28:07.000Z,1.0,[],NaN,NaN,NaN,NaN,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1623,HKI,1,FI,ARRIVAL,True,True,10,False,2025-01-29T13:20:00.000Z,2025-01-29T13:18:32.000Z,-1.0,[],NaN,NaN,NaN,NaN,NaN,64420
1624,ILR,1030,FI,DEPARTURE,True,True,797,False,2025-01-29T13:11:00.000Z,2025-01-29T13:12:02.000Z,1.0,[],NaN,NaN,NaN,NaN,NaN,64422
1625,PSL,10,FI,ARRIVAL,False,NaN,7,False,2025-01-29T13:21:00.000Z,2025-01-29T13:16:19.000Z,-5.0,[],NaN,NaN,NaN,NaN,NaN,64422
1626,PSL,10,FI,DEPARTURE,False,NaN,7,False,2025-01-29T13:21:00.000Z,2025-01-29T13:16:19.000Z,-5.0,[],NaN,NaN,NaN,NaN,NaN,64422
1627,HKI,1,FI,ARRIVAL,True,True,9,False,2025-01-29T13:26:00.000Z,2025-01-29T13:23:00.000Z,-3.0,[],NaN,NaN,NaN,NaN,NaN,64422

#### Tehtävä 5. Pudota sitten seuraavat sarakkeet datasta: `causes`, `differenceInMinutes` ja `commercialStop`

In [5]:
new_timetable_df = timetable_df.drop(["causes","differenceInMinutes","commercialStop"], axis=1)
new_timetable_df

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialTrack,cancelled,scheduledTime,actualTime,trainReady.source,trainReady.accepted,trainReady.timestamp,liveEstimateTime,estimateSource,trainNumber
0,HKI,1,FI,DEPARTURE,True,9,False,2025-01-29T13:19:00.000Z,2025-01-29T13:19:16.000Z,KUPLA,True,2025-01-29T13:04:24.000Z,NaN,NaN,7
1,PSL,10,FI,ARRIVAL,True,4,False,2025-01-29T13:24:00.000Z,2025-01-29T13:24:06.000Z,NaN,NaN,NaN,NaN,NaN,7
2,PSL,10,FI,DEPARTURE,True,4,False,2025-01-29T13:25:00.000Z,2025-01-29T13:25:48.000Z,NaN,NaN,NaN,NaN,NaN,7
3,KÄP,977,FI,ARRIVAL,False,,False,2025-01-29T13:27:00.000Z,2025-01-29T13:28:07.000Z,NaN,NaN,NaN,NaN,NaN,7
4,KÄP,977,FI,DEPARTURE,False,,False,2025-01-29T13:27:00.000Z,2025-01-29T13:28:07.000Z,NaN,NaN,NaN,NaN,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1623,HKI,1,FI,ARRIVAL,True,10,False,2025-01-29T13:20:00.000Z,2025-01-29T13:18:32.000Z,NaN,NaN,NaN,NaN,NaN,64420
1624,ILR,1030,FI,DEPARTURE,True,797,False,2025-01-29T13:11:00.000Z,2025-01-29T13:12:02.000Z,NaN,NaN,NaN,NaN,NaN,64422
1625,PSL,10,FI,ARRIVAL,False,7,False,2025-01-29T13:21:00.000Z,2025-01-29T13:16:19.000Z,NaN,NaN,NaN,NaN,NaN,64422
1626,PSL,10,FI,DEPARTURE,False,7,False,2025-01-29T13:21:00.000Z,2025-01-29T13:16:19.000Z,NaN,NaN,NaN,NaN,NaN,64422
1627,HKI,1,FI,ARRIVAL,True,9,False,2025-01-29T13:26:00.000Z,2025-01-29T13:23:00.000Z,NaN,NaN,NaN,NaN,NaN,64422

#### Tehtävä 6. Täytä jokaisen rivin sarakkeen `actualTime` puuttuvat arvot `scheduledTime` -sarakkeen arvolla.

In [6]:
new_timetable_df['actualTime'] = new_timetable_df['actualTime'].fillna(new_timetable_df['scheduledTime'])
#vanha tapa:
#new_timetable_df['actualTime'].fillna(new_timetable_df['scheduledTime'], inplace=True)
new_timetable_df

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialTrack,cancelled,scheduledTime,actualTime,trainReady.source,trainReady.accepted,trainReady.timestamp,liveEstimateTime,estimateSource,trainNumber
0,HKI,1,FI,DEPARTURE,True,9,False,2025-01-29T13:19:00.000Z,2025-01-29T13:19:16.000Z,KUPLA,True,2025-01-29T13:04:24.000Z,NaN,NaN,7
1,PSL,10,FI,ARRIVAL,True,4,False,2025-01-29T13:24:00.000Z,2025-01-29T13:24:06.000Z,NaN,NaN,NaN,NaN,NaN,7
2,PSL,10,FI,DEPARTURE,True,4,False,2025-01-29T13:25:00.000Z,2025-01-29T13:25:48.000Z,NaN,NaN,NaN,NaN,NaN,7
3,KÄP,977,FI,ARRIVAL,False,,False,2025-01-29T13:27:00.000Z,2025-01-29T13:28:07.000Z,NaN,NaN,NaN,NaN,NaN,7
4,KÄP,977,FI,DEPARTURE,False,,False,2025-01-29T13:27:00.000Z,2025-01-29T13:28:07.000Z,NaN,NaN,NaN,NaN,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1623,HKI,1,FI,ARRIVAL,True,10,False,2025-01-29T13:20:00.000Z,2025-01-29T13:18:32.000Z,NaN,NaN,NaN,NaN,NaN,64420
1624,ILR,1030,FI,DEPARTURE,True,797,False,2025-01-29T13:11:00.000Z,2025-01-29T13:12:02.000Z,NaN,NaN,NaN,NaN,NaN,64422
1625,PSL,10,FI,ARRIVAL,False,7,False,2025-01-29T13:21:00.000Z,2025-01-29T13:16:19.000Z,NaN,NaN,NaN,NaN,NaN,64422
1626,PSL,10,FI,DEPARTURE,False,7,False,2025-01-29T13:21:00.000Z,2025-01-29T13:16:19.000Z,NaN,NaN,NaN,NaN,NaN,64422
1627,HKI,1,FI,ARRIVAL,True,9,False,2025-01-29T13:26:00.000Z,2025-01-29T13:23:00.000Z,NaN,NaN,NaN,NaN,NaN,64422

## Vaihe 2

#### Tehtävä 7. Pura tämän kansion sisällä olevan `data.html` -tiedoston `table`-elementin solujen arvot käyttäen regex-syntaksia ja yhdistä ne vaiheessa 1 luotuun dataframeen. Huom: tehtävässä tulee käyttää vain regexiä (Esim. Pandasin read_html()-metodin käyttö on kielletty)!

In [7]:
import re

with open('data.html', 'r', encoding='utf-8') as file:
    html_content = file.read()

#patternit
table_pattern = r'<table.*?>(.*?)</table>'
cell_pattern = r'<td.*?>(.*?)</td>'

#määritellään ensin, miten haetaan
table_match = re.search(table_pattern, html_content, re.DOTALL)
if table_match:
    table_html = table_match.group(1)
    cell_matches = re.findall(cell_pattern, table_html, re.DOTALL)

    #tämän jälkeen, mitä haetaan
    columns = ["actualTime", "cancelled", "commercialTrack", 
               "countryCode", "scheduledTime", "stationShortCode", 
               "stationUICCode", "trainStopping", "type", "trainNumber"]

    
    num_columns = len(columns)
    num_cells = len(cell_matches)
    
    #ja vielä, mitä tehdään datalle, eli yhdistetään ne toisiinsa
    data_rows = [cell_matches[i:i + num_columns] for i in range(0, num_cells, num_columns)]
    df = pd.DataFrame(data_rows, columns=columns)

    
df

,actualTime,cancelled,commercialTrack,countryCode,scheduledTime,stationShortCode,stationUICCode,trainStopping,type,trainNumber
0,\n 2019-08-06T04:48:00....,\n False\n,\n \n,\n FI\n,\n 2019-08-06T04:48:00....,\n JVS\t\n,\n 1272\n,\n False\n,\n DEPARTURE\n ...,\n 150\n
1,\n 2019-08-06T06:04:39....,\n False\n,\n\n,\n FI\n,\n 2019-08-06T06:04:39....,\n R702\n,\n 98998\n,\n False\n,\n ARRIVAL\n ...,\n 150\n
2,\n 2019-08-06T07:03:12....,\n False\n,\n \n,\n FI\n,\n 2019-08-06T07:03:12....,\n ILA\n,\n 98998\n,\n 9\n,\n ARRIVAL\n ...,\n 8337\n

## Vaihe 3

#### Tehtävä 8. Tee SQLite tietokanta ja lisää sinne vaiheen 2 tuloksena saatu dataframe.

In [8]:
import sqlite3


harkka_base = sqlite3.connect("harkka.db")
connection = harkka_base.cursor()

In [9]:
table_query="""
CREATE TABLE IF NOT EXISTS train_data (
    actualTime TEXT,
    cancelled TEXT,
    commercialTrack TEXT,
    countryCode TEXT,
    scheduledTime TEXT,
    stationShortCode TEXT,
    stationUICCode TEXT,
    trainStopping TEXT,
    type TEXT,
    trainNumber TEXT
)
"""
connection.execute(table_query)

for row in df.values:
    connection.execute("INSERT INTO train_data VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", tuple(row))

In [10]:

harkka_base.commit()
harkka_base.close()

print("Data lisätty onnistuneesti")

Data lisätty onnistuneesti