## Harjoitustyö

## Vaihe 1

#### Tehtävä 1. Hae Digitrafficin REST-rajapintapalvelusta (JSON-formaatissa) aktiiviset junat pääteosoitteella `/live-trains` Helsingin asemalta, joiden hakuparametrit ovat seuraavat:
* arrived_trains=10
* departed_trains=10
* include_nonstopping=False

In [1]:
import requests

url = 'https://rata.digitraffic.fi/api/v1/live-trains/station/HKI?arrived_trains=10&departed_trains=10&include_nonstopping=False'
req_juna = requests.get(url=url)
req_juna.url
req_juna.status_code
juna_data = req_juna.json()
#juna_data

#### Tehtävä 2. Tämän jälkeen lue kyseinen data Pandasin dataframeen ilman muokkaamista, jolloin sarakkeiden otsikot ovat seuraavanlaiset:

 `cancelled`,
 `commuterLineID`,
 `departureDate`,
 `operatorShortCode`,
 `operatorUICCode`,
 `runningCurrently`,
 `timeTableRows`,
 `timetableAcceptanceDate`,
 `timetableType`,
 `trainCategory`,
 `trainNumber`,
 `trainType`,
 `version`

In [2]:
import pandas as pd

junat_df = pd.DataFrame(juna_data)
junat_df

,trainNumber,departureDate,operatorUICCode,operatorShortCode,trainType,trainCategory,commuterLineID,runningCurrently,cancelled,version,timetableType,timetableAcceptanceDate,timeTableRows
0,27,2023-10-14,10,vr,IC,Long-distance,,True,False,286685778667,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
1,46,2023-10-14,10,vr,IC,Long-distance,,True,False,286685802268,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'VS', 'stationUICCode': ..."
2,67,2023-10-14,10,vr,S,Long-distance,,True,False,286685799533,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
3,175,2023-10-14,10,vr,IC,Long-distance,,True,False,286685797517,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
4,956,2023-10-14,10,vr,IC,Long-distance,,False,False,286685802267,REGULAR,2023-02-16T07:07:26.000Z,"[{'stationShortCode': 'KUT', 'stationUICCode':..."
5,8112,2023-10-14,10,vr,HL,Commuter,A,False,False,286685721913,REGULAR,2023-05-11T05:02:32.000Z,"[{'stationShortCode': 'LPV', 'stationUICCode':..."
6,8117,2023-10-14,10,vr,HL,Commuter,A,False,False,286685759834,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
7,8123,2023-10-14,10,vr,HL,Commuter,A,False,False,286666477271,REGULAR,2023-05-11T05:02:32.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
8,8352,2023-10-14,10,vr,HL,Commuter,E,True,False,286685802268,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'KLH', 'stationUICCode':..."
9,8355,2023-10-14,10,vr,HL,Commuter,E,False,False,286668968694,REGULAR,2022-12-15T06:04:43.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
10,8466,2023-10-14,10,vr,HL,Commuter,U,False,False,286685749421,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'KKN', 'stationUICCode':..."
11,8471,2023-10-14,10,vr,HL,Commuter,U,True,False,286685795456,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
12,8666,2023-10-14,10,vr,HL,Commuter,P,False,False,286685736936,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
13,8669,2023-10-14,10,vr,HL,Commuter,P,True,False,286685802267,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
14,8674,2023-10-14,10,vr,HL,Commuter,P,True,False,286685795456,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
15,8675,2023-10-14,10,vr,HL,Commuter,P,True,False,286685797518,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
16,8677,2023-10-14,10,vr,HL,Commuter,P,False,False,286685748937,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
17,8861,2023-10-14,10,vr,HL,Commuter,I,False,False,286685704051,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'LEN', 'stationUICCode':..."
18,8862,2023-10-14,10,vr,HL,Commuter,I,False,False,286685760252,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
19,8864,2023-10-14,10,vr,HL,Commuter,I,True,False,286685789498,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'LEN', 'stationUICCode':..."
20,8870,2023-10-14,10,vr,HL,Commuter,I,True,False,286685800251,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
21,8873,2023-10-14,10,vr,HL,Commuter,I,False,False,286680797320,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
22,9134,2023-10-14,10,vr,HL,Commuter,K,False,False,286685682533,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'KE', 'stationUICCode': ..."
23,9140,2023-10-14,10,vr,HL,Commuter,K,True,False,286685792243,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'KE', 'stationUICCode': ..."
24,9163,2023-10-14,10,vr,HL,Commuter,K,True,False,286685776992,REGULAR,2023-07-05T11:22:01.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
25,9670,2023-10-14,10,vr,HL,Commuter,R,False,False,286685798977,REGULAR,2023-05-11T05:02:32.000Z,"[{'stationShortCode': 'RI', 'stationUICCode': ..."
26,9681,2023-10-14,10,vr,HL,Commuter,R,True,False,286685784164,REGULAR,2023-05-11T05:02:32.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."
27,9836,2023-10-14,10,vr,HL,Commuter,Z,False,False,286685754834,REGULAR,2023-05-11T05:02:32.000Z,"[{'stationShortCode': 'LH', 'stationUICCode': ..."
28,65102,2023-10-14,10,vr,SAA,Shunting,,False,False,286685759834,ADHOC,2023-10-14T09:35:28.000Z,"[{'stationShortCode': 'ILR', 'stationUICCode':..."
29,65103,2023-10-14,10,vr,SAA,Shunting,,False,False,286685475902,ADHOC,2023-10-14T09:36:20.000Z,"[{'stationShortCode': 'HKI', 'stationUICCode':..."

#### Tehtävä 3. Poista kaikki muut sarakkeet paitsi `timeTableRows` ja `trainNumber`

In [3]:
train_info = junat_df.drop(["cancelled", "commuterLineID", "departureDate", 
                     "operatorShortCode", "operatorUICCode", "runningCurrently", 
                     "timetableAcceptanceDate", "timetableType", "trainCategory", 
                     "trainType", "version"], axis=1)
train_info

    trainNumber                                      timeTableRows
0            27  [{'stationShortCode': 'HKI', 'stationUICCode':...
1            46  [{'stationShortCode': 'VS', 'stationUICCode': ...
2            67  [{'stationShortCode': 'HKI', 'stationUICCode':...
3           175  [{'stationShortCode': 'HKI', 'stationUICCode':...
4           956  [{'stationShortCode': 'KUT', 'stationUICCode':...
5          8112  [{'stationShortCode': 'LPV', 'stationUICCode':...
6          8117  [{'stationShortCode': 'HKI', 'stationUICCode':...
7          8123  [{'stationShortCode': 'HKI', 'stationUICCode':...
8          8352  [{'stationShortCode': 'KLH', 'stationUICCode':...
9          8355  [{'stationShortCode': 'HKI', 'stationUICCode':...
10         8466  [{'stationShortCode': 'KKN', 'stationUICCode':...
11         8471  [{'stationShortCode': 'HKI', 'stationUICCode':...
12         8666  [{'stationShortCode': 'HKI', 'stationUICCode':...
13         8669  [{'stationShortCode': 'HKI', 'stationUICCode':...
14         8674  [{'stationShortCode': 'HKI', 'stationUICCode':...
15         8675  [{'stationShortCode': 'HKI', 'stationUICCode':...
16         8677  [{'stationShortCode': 'HKI', 'stationUICCode':...
17         8861  [{'stationShortCode': 'LEN', 'stationUICCode':...
18         8862  [{'stationShortCode': 'HKI', 'stationUICCode':...
19         8864  [{'stationShortCode': 'LEN', 'stationUICCode':...
20         8870  [{'stationShortCode': 'HKI', 'stationUICCode':...
21         8873  [{'stationShortCode': 'HKI', 'stationUICCode':...
22         9134  [{'stationShortCode': 'KE', 'stationUICCode': ...
23         9140  [{'stationShortCode': 'KE', 'stationUICCode': ...
24         9163  [{'stationShortCode': 'HKI', 'stationUICCode':...
25         9670  [{'stationShortCode': 'RI', 'stationUICCode': ...
26         9681  [{'stationShortCode': 'HKI', 'stationUICCode':...
27         9836  [{'stationShortCode': 'LH', 'stationUICCode': ...
28        65102  [{'stationShortCode': 'ILR', 'stationUICCode':...
29        65103  [{'stationShortCode': 'HKI', 'stationUICCode':...

#### Tehtävä 4. Tämän jälkeen pura `timeTableRows` sarakkeen arvot jokaisesta junasta erikseen (sarakkeen arvo jokaiselle junalle sisältää useampia JSON-objekteja) ja lisää dataan mukaan junan tiedot yksilöivä `trainNumber`

In [4]:
from pandas import json_normalize

timetable_df = pd.DataFrame()

# Käy läpi alkuperäisen DataFrameen rivit
for index, row in junat_df.iterrows():
    train_number = row['trainNumber']
    time_table_rows = row['timeTableRows']
    
    # Purkaa JSON-tiedot ja lisää ne uuteen DataFrameen
    train_df = json_normalize(time_table_rows)
    train_df['trainNumber'] = train_number
    
    timetable_df = pd.concat([timetable_df, train_df], ignore_index=True)
timetable_df

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialStop,commercialTrack,cancelled,scheduledTime,actualTime,differenceInMinutes,causes,trainNumber,trainReady.source,trainReady.accepted,trainReady.timestamp,liveEstimateTime,estimateSource
0,HKI,1,FI,DEPARTURE,True,True,7,False,2023-10-14T11:20:00.000Z,2023-10-14T11:20:44.000Z,1.0,[],27,KUPLA,True,2023-10-14T11:09:28.000Z,NaN,NaN
1,PSL,10,FI,ARRIVAL,True,True,3,False,2023-10-14T11:25:00.000Z,NaN,0.0,[],27,NaN,NaN,NaN,2023-10-14T11:25:09.000Z,COMBOCALC
2,PSL,10,FI,DEPARTURE,True,True,3,False,2023-10-14T11:26:00.000Z,NaN,0.0,[],27,NaN,NaN,NaN,2023-10-14T11:26:09.000Z,COMBOCALC
3,KÄP,977,FI,ARRIVAL,False,NaN,,False,2023-10-14T11:28:00.000Z,NaN,0.0,[],27,NaN,NaN,NaN,2023-10-14T11:28:16.000Z,COMBOCALC
4,KÄP,977,FI,DEPARTURE,False,NaN,,False,2023-10-14T11:28:00.000Z,NaN,0.0,[],27,NaN,NaN,NaN,2023-10-14T11:28:16.000Z,COMBOCALC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,HKI,1,FI,ARRIVAL,True,True,6,False,2023-10-14T11:21:00.000Z,2023-10-14T11:19:43.000Z,-1.0,[],65102,NaN,NaN,NaN,NaN,NaN
1652,HKI,1,FI,DEPARTURE,True,True,8,False,2023-10-14T11:32:00.000Z,NaN,NaN,[],65103,NaN,NaN,NaN,NaN,NaN
1653,PSL,10,FI,ARRIVAL,False,NaN,,False,2023-10-14T11:36:00.000Z,NaN,NaN,[],65103,NaN,NaN,NaN,NaN,NaN
1654,PSL,10,FI,DEPARTURE,False,NaN,,False,2023-10-14T11:36:00.000Z,NaN,NaN,[],65103,NaN,NaN,NaN,NaN,NaN
1655,ILR,1030,FI,ARRIVAL,True,True,755,False,2023-10-14T11:46:00.000Z,NaN,NaN,[],65103,NaN,NaN,NaN,NaN,NaN

#### Tehtävä 5. Pudota sitten seuraavat sarakkeet datasta: `causes`, `differenceInMinutes` ja `commercialStop`

In [5]:
new_timetable_df = timetable_df.drop(["causes","differenceInMinutes","commercialStop"], axis=1)
new_timetable_df

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialTrack,cancelled,scheduledTime,actualTime,trainNumber,trainReady.source,trainReady.accepted,trainReady.timestamp,liveEstimateTime,estimateSource
0,HKI,1,FI,DEPARTURE,True,7,False,2023-10-14T11:20:00.000Z,2023-10-14T11:20:44.000Z,27,KUPLA,True,2023-10-14T11:09:28.000Z,NaN,NaN
1,PSL,10,FI,ARRIVAL,True,3,False,2023-10-14T11:25:00.000Z,NaN,27,NaN,NaN,NaN,2023-10-14T11:25:09.000Z,COMBOCALC
2,PSL,10,FI,DEPARTURE,True,3,False,2023-10-14T11:26:00.000Z,NaN,27,NaN,NaN,NaN,2023-10-14T11:26:09.000Z,COMBOCALC
3,KÄP,977,FI,ARRIVAL,False,,False,2023-10-14T11:28:00.000Z,NaN,27,NaN,NaN,NaN,2023-10-14T11:28:16.000Z,COMBOCALC
4,KÄP,977,FI,DEPARTURE,False,,False,2023-10-14T11:28:00.000Z,NaN,27,NaN,NaN,NaN,2023-10-14T11:28:16.000Z,COMBOCALC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,HKI,1,FI,ARRIVAL,True,6,False,2023-10-14T11:21:00.000Z,2023-10-14T11:19:43.000Z,65102,NaN,NaN,NaN,NaN,NaN
1652,HKI,1,FI,DEPARTURE,True,8,False,2023-10-14T11:32:00.000Z,NaN,65103,NaN,NaN,NaN,NaN,NaN
1653,PSL,10,FI,ARRIVAL,False,,False,2023-10-14T11:36:00.000Z,NaN,65103,NaN,NaN,NaN,NaN,NaN
1654,PSL,10,FI,DEPARTURE,False,,False,2023-10-14T11:36:00.000Z,NaN,65103,NaN,NaN,NaN,NaN,NaN
1655,ILR,1030,FI,ARRIVAL,True,755,False,2023-10-14T11:46:00.000Z,NaN,65103,NaN,NaN,NaN,NaN,NaN

#### Tehtävä 6. Täytä jokaisen rivin sarakkeen `actualTime` puuttuvat arvot `scheduledTime` -sarakkeen arvolla.

In [6]:
new_timetable_df['actualTime'].fillna(new_timetable_df['scheduledTime'], inplace=True)
new_timetable_df

,stationShortCode,stationUICCode,countryCode,type,trainStopping,commercialTrack,cancelled,scheduledTime,actualTime,trainNumber,trainReady.source,trainReady.accepted,trainReady.timestamp,liveEstimateTime,estimateSource
0,HKI,1,FI,DEPARTURE,True,7,False,2023-10-14T11:20:00.000Z,2023-10-14T11:20:44.000Z,27,KUPLA,True,2023-10-14T11:09:28.000Z,NaN,NaN
1,PSL,10,FI,ARRIVAL,True,3,False,2023-10-14T11:25:00.000Z,2023-10-14T11:25:00.000Z,27,NaN,NaN,NaN,2023-10-14T11:25:09.000Z,COMBOCALC
2,PSL,10,FI,DEPARTURE,True,3,False,2023-10-14T11:26:00.000Z,2023-10-14T11:26:00.000Z,27,NaN,NaN,NaN,2023-10-14T11:26:09.000Z,COMBOCALC
3,KÄP,977,FI,ARRIVAL,False,,False,2023-10-14T11:28:00.000Z,2023-10-14T11:28:00.000Z,27,NaN,NaN,NaN,2023-10-14T11:28:16.000Z,COMBOCALC
4,KÄP,977,FI,DEPARTURE,False,,False,2023-10-14T11:28:00.000Z,2023-10-14T11:28:00.000Z,27,NaN,NaN,NaN,2023-10-14T11:28:16.000Z,COMBOCALC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,HKI,1,FI,ARRIVAL,True,6,False,2023-10-14T11:21:00.000Z,2023-10-14T11:19:43.000Z,65102,NaN,NaN,NaN,NaN,NaN
1652,HKI,1,FI,DEPARTURE,True,8,False,2023-10-14T11:32:00.000Z,2023-10-14T11:32:00.000Z,65103,NaN,NaN,NaN,NaN,NaN
1653,PSL,10,FI,ARRIVAL,False,,False,2023-10-14T11:36:00.000Z,2023-10-14T11:36:00.000Z,65103,NaN,NaN,NaN,NaN,NaN
1654,PSL,10,FI,DEPARTURE,False,,False,2023-10-14T11:36:00.000Z,2023-10-14T11:36:00.000Z,65103,NaN,NaN,NaN,NaN,NaN
1655,ILR,1030,FI,ARRIVAL,True,755,False,2023-10-14T11:46:00.000Z,2023-10-14T11:46:00.000Z,65103,NaN,NaN,NaN,NaN,NaN

## Vaihe 2

#### Tehtävä 7. Pura tämän kansion sisällä olevan `data.html` -tiedoston `table`-elementin solujen arvot käyttäen regex-syntaksia ja yhdistä ne vaiheessa 1 luotuun dataframeen. Huom: tehtävässä tulee käyttää vain regexiä (Esim. Pandasin read_html()-metodin käyttö on kielletty)!

In [7]:
import re

with open('data.html', 'r', encoding='utf-8') as file:
    html_content = file.read()

#patternit
table_pattern = r'<table.*?>(.*?)</table>'
cell_pattern = r'<td.*?>(.*?)</td>'

table_match = re.search(table_pattern, html_content, re.DOTALL)
if table_match:
    table_html = table_match.group(1)
    cell_matches = re.findall(cell_pattern, table_html, re.DOTALL)

    
    columns = ["actualTime", "cancelled", "commercialTrack", 
               "countryCode", "scheduledTime", "stationShortCode", 
               "stationUICCode", "trainStopping", "type", "trainNumber"]
    df = pd.DataFrame(columns=columns)

    
    num_columns = len(columns)
    num_cells = len(cell_matches)
    
    for i in range(num_rows):
        df = pd.concat([df, pd.DataFrame([cell_data], columns=columns)], ignore_index=True)

    
df

NameError: name 'num_rows' is not defined

## Vaihe 3

#### Tehtävä 8. Tee SQLite tietokanta ja lisää sinne vaiheen 2 tuloksena saatu dataframe.

In [ ]:
import sqlite3


harkka_base = sqlite3.connect("harkka.db")

In [ ]:
connection = testi_base.cursor()

In [ ]:
df_to_sql = df.copy()
df_to_sql.to_sql(name="harkka.db", con=harkka_base, if_exists='replace', index=False)
df_to_sql

In [ ]:
harkka_base.close()